### ISSUE TITLE
Background data set error

### ISSUE THREAD

**Issue by aflores09** [alexblaessle/PyFDAP#2]
Hello,

I am having a problem uploading my background csv dataset.  I used the same excel template for the embryo data but I am getting this error.  

````
AttributeError: bkgd_dataset instance has no attribute 'ext_vec'
Traceback (most recent call last):
  File "pyfdap\pyfdap_subwin.py", line 5069, in done_pressed
  File "pyfdap\pyfdap_misc_module.py", line 688, in gen_bkgds_from_csv
AttributeError: bkgd_dataset instance has no attribute 'ext_vec'
````

Not exactly sure how to correct it so that I can plot the maindata set while the background data set is imported.

I tried to attach my experimental dataset and my background dataset but it won't accept csv format.  I have attached an excel workbook version
[Background2 - Copy.xlsx](https://github.com/alexblaessle/PyFDAP/files/733445/Background2.-.Copy.xlsx)
  Any help would be great!  Thank you!

Sincerely,
[d2 basal - Copy.xlsx](https://github.com/alexblaessle/PyFDAP/files/733447/d2.basal.-.Copy.xlsx)

AFB

**Comment by alexblaessle** [comment]
Hi Andrea, 

Thanks for finding the bug. Turns out that ``bkgd_dataset`` does not have the attribute ``ext_vec`` but ``bkgd_ext_vec``. Fixed in commit https://github.com/alexblaessle/PyFDAP/commit/62c87a0c837a32c925533f7395339c4a3da52a0d . I will create executables ASAP.

**Comment by aflores09** [comment]
Wonderful thank you!

**Comment by aflores09** [comment]
Please let me know when you put the updated version of pyFDAP in dropbox.
Thank you!

Sincerely,

Andrea

**Comment by aflores09** [comment]
Hi Alex,

Sorry to be bothersome but my advisor is nudging me to finalize my data
set.  At your earliest convenience please let me know when you share the
updates in drop box.  Thank you.  Take care.

Andrea
